### ISSUE TITLE
Tuner plugin

### ISSUE THREAD

**Issue by robnorr** [afms135/signl#10]
not sure how possible

**Comment by robnorr** [comment]
Maybe better if made as another screen - via pushing the button

**Comment by robnorr** [comment]
Achieved via af4ef87c2833d9f289b5b653fc9419dccaee8651
Written as a 3rd disply state (after param_view and level_view). Has a resolution of 1.46Hz

**Comment by robnorr** [comment]
Not merging to master as it isn't really a useful implementation. Video and description on Wiki [here](https://github.com/afms135/signl/wiki/Tuner).

**Comment by afms135** [comment]
Just copying what i said [Here](https://github.com/afms135/signl/commit/af4ef87c2833d9f289b5b653fc9419dccaee8651#comments) not sure if you get notifications.

Shouldn't line 193 of signl.cpp read `fft.fft(tuner_array, fft_re.data(), fft_im.data());` You are filling tuner_array but not using it?

Would that fix the segfault?

**Comment by robnorr** [comment]
Good catch! It definitely should be `fft.fft(tuner_array, ...`. That makes it respond much better. Will upload a new video.

But it deosn't seem to fix the segfault.

**Comment by robnorr** [comment]
a5d5e1dc2916b91e8277dcb96f08fcf834b55c6b
Added gaussian interpolation and windowing inspired from [this paper](http://cds.cern.ch/record/738182/files/ab-2004-023).
Need to write up wiki (and record a demonstration video) and check that all relevant Doxygen documentation is done.

**Comment by robnorr** [comment]
Closed by 7fdb2a437a745f4626878dc81359b5585256b6f4
