### ISSUE TITLE
Add licence.

### ISSUE THREAD

**Issue by afms135** [afms135/signl#17]

**Comment by robnorr** [comment]
Just to note https://github.com/afms135/signl/issues/4#issuecomment-608591309
So this project now uses [FFTConvolver](https://github.com/HiFi-LoFi/FFTConvolver)

**Comment by afms135** [comment]
I'm assuming GPLv3 is ok for everyone? (This is compatible with FFTConvolver)

**Comment by robnorr** [comment]
I don't have any issue with that

**Comment by afms135** [comment]
Fixed by 2e5afd5ce1507044af8c49c7ff1aee50c2219f10
