### ISSUE TITLE
EQ plugin

### ISSUE THREAD

**Issue by afms135** [afms135/signl#2]
Add an 4-band? equalizer plugin.

**Comment by robnorr** [comment]
Or could be 3-band with the fourth parameter being the mid-freqency

**Comment by robnorr** [comment]
Closed by d951ab6a34f3c8e1103f7d8e63b02f41674feea6

**Comment by robnorr** [comment]
If anyone wants to reopen this issue, I believe there is a slight bump at the filter overlaps - all filters are 1st order butterworth, the xover frequencies are (150Hz, 300Hz, 3kHz). 'Low' is a lowpass, 'High' is a highpass, and the other two are bandpass. So, if there is more work to be done on this plugin, can look at the frequency response of all the filters, but for now - it works.
