### ISSUE TITLE
ADC values return 0

### ISSUE THREAD

**Issue by robnorr** [afms135/signl#27]
Have checked voltage on the pins of the ADC (MCP3004) - they are what they should be. But the SPI transfer is returning 0 no matter what.

**Comment by ithinkitssimon** [comment]
Have you checked CS line?

**Comment by afms135** [comment]
Try reducing the SPI clock rate to 1000000 (or lower).
I think 2000000 might be too high (line 4 of adc.cpp).

**Comment by robnorr** [comment]
> Have you checked CS line?

On program start up, chip select goes high, then low. The first value read from the ADC works properly, but the chip select never goes high again therefore the rest of the values read are all 0.

So, need to figure out why the chip select line is getting stuck low.

**Comment by robnorr** [comment]
Closed by 1cb5aca4819267a3845c9bf30a77d94539ea7d11
