### ISSUE TITLE
Deleting the reverb plugin crashes the signl software

### ISSUE THREAD

**Issue by robnorr** [afms135/signl#33]
If the reverb plugin is being used (see 7ae3209015648144f1a2c41f5cef258c4c02af92 ), and is then deleted (i.e., switched out for another plugin), the signl software crashes and stops, with this being spat out on the terminal:

    signl: ../FFTConvolver/Utilities.cpp:61: void fftconvolver::ComplexMultiplyAccumulate(fftconvolver::SplitComplex&, const fftconvolver::SplitComplex&, const fftconvolver::SplitComplex&): Assertion `result.size() == b.size()' failed.
    Aborted

My guess is that the FFTConvolver object(s) which are created in the reverb plugin aren't destroyed properly, but I can't figure out how to destroy them properly.

**Comment by afms135** [comment]
Reorder the classes private members, they are destructed in reverse order. The problem probably is the std::vectors are being destroyed before the FFTConvolvers, so try placing the convolvers last.

**Comment by afms135** [comment]
See a80ed9f68adab00561acb64b48f637278658d37a

**Comment by robnorr** [comment]
Okay, odd behaviour now. Have made the change you suggested, and the problem is fixed for the first time that I switch out the reverb plugin (i.e. it no longer crashes). But, if the plugin is put back in, this time (and for every time after) when I switch it out, it crashes the same way as before.

**Comment by robnorr** [comment]
Note, sometimes it crashes with `Segmentation fault` rather than the above message.

**Comment by robnorr** [comment]
Okay, I tried with just one FFTConvolver at a time and it seems like it was the big long church IR (131,072 samples) that was causing problems. The smaller IR (16,384 samples) on its own never crashes.

**Comment by robnorr** [comment]
Using the TwoStageFFTConvolver has greatly improved this. Still crashes sometimes, but FAR less often.

**Comment by afms135** [comment]
Maybe try changing the type of the impulse arrays to const float[] instead of a vector. But my gut feeling for a long term fix is to compile the fftconvolver code _into_ the so file instead of using dlopen() to load it into the main executable. That would require a makefile change, but I'd rather wait until the plugin is finished before doing that.

**Comment by robnorr** [comment]
Seems pretty stable now. Can only make it crash by switching between the reverb and some other effect really fast repeatedly. But what you say might help, so I'll let you know when I've finished the rest of the plugin

**Comment by robnorr** [comment]
Reverb plugin is finished and ready to be merged as of e27cc37cb5b124e46912d815ed9ad1e6a67f0beb .

It only crashes if you switch it out within ~1 sec of switching onto it, but other than that it's perfect.
@afms135 would you rather I merge to master now, or do you want to make any changes in the branch?

**Comment by afms135** [comment]
Do the merge now, I'll do my work later.

**Comment by afms135** [comment]
Fixed by 7207acab2960d0daf7a8058055e3c33809f3bd66
